base_url = "https://mrec.github.io"
title = "Never Knowingly Undershaved"
description = "Probably programming-related, definitely stupidly-titled"
default_language = "en"
compile_sass = false
build_search_index = false
ignored_content = ["**/*.pdn"]
author = "Mike Capp"
taxonomies = [ { name = "tags" }, ]
generate_feeds = true

[markdown]
external_links_class = "external"
external_links_no_follow = true
external_links_no_referrer = true
highlight_code = true
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_theme = "QuietLight"
insert_anchor_links = "heading"
smart_punctuation = true

[extra]
tag_descriptions = { meta = "this blog itself", performance = "making things go fast(er)", rust = "the Rust programming language" }